### ISSUE TITLE
Collect changes of Resources/Connector in Queue and update at broker separately

### ISSUE THREAD

**Issue by vdakker** [International-Data-Spaces-Association/IDS-ConfigurationManager#87] opened 2021-03-30 10:16 UTC
I'm not sure if we shoud update resources at the Broker in the `ResourceUIController`, because it will add another call Configmanager<->DSC<->Broker into the `updateResource` message (which could cause timeouts or significant slowdown).

Maybe the Configmanager should maintain a Queue of what was Updated/Changed/Added and is not yet commited to the Brokers. Then the Configmanager could handle the Queue independently from the API calls.

_Originally posted by @vdakker in https://github.com/International-Data-Spaces-Association/IDS-ConfigurationManager/issues/83#issuecomment-810042567_

**Comment by goekhanKahriman** [comment] 2021-03-30 10:46
I find this is a good idea
There was also talk that in the future the CM should not be involved in the IDS communication, but that the ui directly makes the calls to the connector itself.
This would have to be discussed

**Comment by tmberthold** [comment] 2021-03-31 06:33
Since the issue is basically a duplicate of Issue #83, I will close it at this point.

In principle, however, I believe that it should be state of the art to be able to reflect changes made directly live, if required. 

In the future, we will look in more detail at the runtime required for API calls to return a response.

**Closed by tmberthold** 2021-03-31 06:33 UTC
Labels: Type: Idea
