### ISSUE TITLE
Access to docker image release is gated by basic auth

### ISSUE THREAD

**Issue by cweiers** [International-Data-Spaces-Association/IDS-ConfigurationManager#139] opened 2021-05-06 11:41 UTC
Hey, 

I wanted to try the configuration manager, but 
`docker pull docker.pkg.github.com/international-data-spaces-association/ids-configurationmanager/configurationmanager:6.0.0`
just gives a `Error response from daemon: Get https://docker.pkg.github.com/v2/international-data-spaces-association/ids-configurationmanager/configurationmanager/manifests/6.0.0: no basic auth credentials`

**Comment by tmberthold** [comment] 2021-05-06 11:46
This will be due to GitHub, a Docker-Login on GitHub is required to download images from the registry from here. For this, a private AccessToken is required in the user settings on GitHub. This can be obtained via the personal account settings.

If there are still problems, please let us know again.

**Comment by tmberthold** [comment] 2021-05-06 12:27
I'll close this for now, as I assume the problem is due to the non-existent Docker-Login local on GitHub. If that is not the problem, please let me know again.

**Closed by tmberthold** 2021-05-06 12:27 UTC
Labels: Status: Feedback Needed, Type: Help Needed
